services:
  wasi-runner:
    build: wasi-runner
    environment:
      S3_BUCKET_NAME: snippy
      S3_ENDPOINT: http://snippy-bucket:9000
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      DB_HOST: snippy-db
      DB_PORT: 5432
      DB_USER: snippyuser
      DB_PASSWORD: snippy123
      DB_NAME: snippy
    ports:
      - 3001:3001
    depends_on:
      - snippy-db
      - snippy-bucket
  snippy-client:
    build: client
    ports:
      - 3000:80
    depends_on:
      - wasi-runner
  snippy-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: snippy
      POSTGRES_USER: snippyuser
      POSTGRES_PASSWORD: snippy123
    healthcheck:
      test: ["CMD-SHELL", "psql -U snippyuser -d snippy -c 'SELECT 1' || exit 1"]
      interval: 5s
      timeout: 30s
      retries: 5
    ports:
      - 2345:2345
    volumes:
      - ./wasi-runner/local_setup.sql:/docker-entrypoint-initdb.d/init.sql
  snippy-bucket:
    image: minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /export/snippy && /usr/bin/minio server /export --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
    ports:
      - 9000:9000
      - 9001:9001
